config/routes.rb
Rails.application.routes.draw do
  #root 'posts#index'


  
  resources :users


  root 'posts#index'

  get    'posts/' =>  'posts#index',    as: :posts

  post   'posts/' =>   'posts#create'

  get    'posts/new' =>       'posts#new', as: :new_post

  get    'posts/:id' =>       'posts#show',     as: :post

  get    'posts/:id/edit' =>  'posts#edit', as: :edit_post

  patch  'posts/:id' =>       'posts#update'

  delete 'posts/:id' =>       'posts#destroy', as: :delete

  controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
   end

   get 'sessions/' => 'sessions#index', as: :sessions


end

app/models/post.rb
class Post
  include Mongoid::Document
  belongs_to :user
  field :title, type: String
  field :content, type: String
  field :userId, type: String
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  has_secure_password

  has_many :posts

  field :email, type: String
  field :password_digest, type: String
 

  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  
  


  def current_user
  	@current_user ||= User.where(id: session[:user_id].to_s).first
  end
  
 

  def authorize
  	redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/posts_controller.rb
	class PostsController < ApplicationController
	def index
	@posts = Post.all
	@users = User.all
	end

	def new
		@post = Post.new
	end

 
	def create 
		@post = Post.new(params.require(:post).permit(:title, :content))
		if @post.save
			redirect_to sessions_path
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update_attributes(params.require(:post).permit(:title, :content))
			redirect_to sessions_path
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to sessions_path
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def index
		@posts = Post.all
		@users = User.all
	end

	def new
		@user = User.new
		@is_login = true
		

	end

	def create
		user = User.where(email: params[:email]).first
		# first make sure we actually find a user
		# then see if user authenticates
		if user && user.authenticate(params[:password])
			# sets the cookie to the browser
			session[:user_id] = user.id.to_s
			redirect_to sessions_path
		else
			flash.now.alert = "Email or password is invalid"
			render "new"
			# redirect_to new_session_path
		end
	end

	def destroy
		# Kill our cookies!
		session[:user_id] = nil
		redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)



      if @user.save
        session[:user_id] = @user.id
       	redirect_to sessions_path
      else
   		render action: 'new' 

      end

  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to sessions_path,
          notice: "User #{@user.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to sessions_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
</head>
<body>
	<div id="container">
		<div id="user_header">
			<% if current_user %>
			  Logged in as <%= current_user.email %>.
			  <%= link_to "Log Out", logout_path %>
			<% else %>
			  <%= link_to "Sign Up", new_user_path %> or
			  <%= link_to "Log In", login_path %>
			<% end %>
		</div>
		<% flash.each do |name,msg| %>
			<%= content_tag :div, msg, id: "flash_#{name}" %>
		<% end %>

		<%= yield %>
	</div>
</body>
</html>

app/views/posts/edit.html.erb
<h1> Edit this post! </h1>

<%= form_for @post do |f| %>

	<%= f.hidden_field :post_id, :value => @post.id %>
	Name: <%= f.text_field :title, placeholder: "title" %>
	<%= f.text_field :content, placeholder: "content"%>
	<%= f.submit "Edit post!" %>

<% end %>

app/views/posts/index.html.erb
<div class="main">
  <% @posts.each do |p| %>
  	<div class="post">
		<strong><%= p.title %></strong> <br>
	    <%= p.content %> <br>
	    <% if current_user %>
	    	<%= link_to 'Edit', edit_post_path(p) %>
	    	<%= link_to 'Delete', post_path(p), method: :delete, data: { confirm: 'Are you sure?' } %>
	    <%end%>
	</div>
   <% end %>
   <% if current_user %>
	<div class = "newPost">
		<%= link_to 'Add New Post', new_post_path(@post) %>
	</div>
	<%end%>
	</div>

app/views/posts/new.html.erb
 <%= form_for Post.new do |p| %>
 <%=hidden_field_tag :post_id, @post.id%>

	Title<%= p.text_field :title %> <br/>
	Content <%= p.text_area :content %><br />

	<%= p.submit "Add Post!" %>


<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%=@post.title%><br>
   <%=@post.content%><br>
</p>


<%= link_to "Show All Posts", posts_path %>
<%= link_to "Delete This Post", post_path(@post), :confirm => 'Are you sure?', :method => :delete %>

app/views/users/index.html.erb
<!-- <h1>user index</h1>


<% @users.each do |u| %>
<%=current_user.id %>
<%=@user.id %>
<%end%>
 -->

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
 <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit%>
<%end%>